/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 29 17:21:01 GMT 2018
 */

package persistence;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import persistence.SQLFile;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SQLFile_ESTest extends SQLFile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      SQLFile sQLFile0 = new SQLFile("`XI^J(Y&9B]S5&5", "\u0392", stringArray0, true);
      sQLFile0.close();
      sQLFile0.close();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      SQLFile sQLFile0 = new SQLFile("9>/sZ[c^,ZZckOL`", "9>/sZ[c^,ZZckOL`", stringArray0, true);
      Object[] objectArray0 = new Object[2];
      // Undeclared exception!
      try { 
        sQLFile0.write(objectArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // SQL file has 0 columns but you provided 2 fields
         //
         verifyException("persistence.SQLFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[0];
      SQLFile sQLFile0 = new SQLFile("n<pG:A", "i:.,g7*CJ >SQ1", stringArray0, false);
      sQLFile0.close();
      // Undeclared exception!
      try { 
        sQLFile0.write(stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Error, writing to a closed SQL file.
         //
         verifyException("persistence.SQLFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[0];
      SQLFile sQLFile0 = new SQLFile("n<pG:A", "i:.,g7*CJ >SQ1", stringArray0, false);
      sQLFile0.write(stringArray0);
      sQLFile0.close();
  }
}
