/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 29 17:19:36 GMT 2018
 */

package role;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import role.MappingStrategyConfigurator;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MappingStrategyConfigurator_ESTest extends MappingStrategyConfigurator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        MappingStrategyConfigurator.fromJSON("4");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MappingStrategyConfigurator mappingStrategyConfigurator0 = new MappingStrategyConfigurator();
  }
}
