/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 29 17:16:51 GMT 2018
 */

package heuristics;

import org.junit.Test;
import static org.junit.Assert.*;
import heuristics.UnrecognizedHeuristicKey;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnrecognizedHeuristicKey_ESTest extends UnrecognizedHeuristicKey_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnrecognizedHeuristicKey unrecognizedHeuristicKey0 = new UnrecognizedHeuristicKey();
  }
}
