/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 29 17:14:06 GMT 2018
 */

package heuristics.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import heuristics.AnalysedFile;
import heuristics.ConfigurableHeuristics;
import heuristics.java.AnnotationHeuristics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.repodriller.domain.Modification;
import org.repodriller.domain.ModificationType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnnotationHeuristics_ESTest extends AnnotationHeuristics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnnotationHeuristics annotationHeuristics0 = new AnnotationHeuristics();
      String[] stringArray0 = new String[6];
      try { 
        annotationHeuristics0.configureHeuristic("ADD", stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("heuristics.java.AnnotationHeuristics", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AnnotationHeuristics annotationHeuristics0 = new AnnotationHeuristics();
      String[] stringArray0 = new String[2];
      ConfigurableHeuristics configurableHeuristics0 = annotationHeuristics0.configureHeuristic("onInterface", stringArray0);
      assertSame(configurableHeuristics0, annotationHeuristics0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AnnotationHeuristics annotationHeuristics0 = new AnnotationHeuristics();
      String[] stringArray0 = new String[7];
      ConfigurableHeuristics configurableHeuristics0 = annotationHeuristics0.configureHeuristic("onClass", stringArray0);
      assertSame(annotationHeuristics0, configurableHeuristics0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AnnotationHeuristics annotationHeuristics0 = new AnnotationHeuristics();
      String[] stringArray0 = new String[3];
      ConfigurableHeuristics configurableHeuristics0 = annotationHeuristics0.configureHeuristic("onField", stringArray0);
      assertSame(configurableHeuristics0, annotationHeuristics0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AnnotationHeuristics annotationHeuristics0 = new AnnotationHeuristics();
      ModificationType modificationType0 = ModificationType.COPY;
      Modification modification0 = new Modification("onField", "onField", modificationType0, "onField", "onField");
      AnalysedFile analysedFile0 = new AnalysedFile(modification0);
      Boolean boolean0 = annotationHeuristics0.getRole(analysedFile0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AnnotationHeuristics annotationHeuristics0 = new AnnotationHeuristics();
      String string0 = annotationHeuristics0.getName();
      assertEquals("annotation", string0);
  }
}
