/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 29 17:16:46 GMT 2018
 */

package heuristics.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import heuristics.AnalysedFile;
import heuristics.ConfigurableHeuristics;
import heuristics.java.ClassNameHeuristics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.repodriller.domain.Modification;
import org.repodriller.domain.ModificationType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClassNameHeuristics_ESTest extends ClassNameHeuristics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClassNameHeuristics classNameHeuristics0 = new ClassNameHeuristics();
      String[] stringArray0 = new String[8];
      try { 
        classNameHeuristics0.configureHeuristic("Operation only supported in JLS4 and later AST", stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("heuristics.java.ClassNameHeuristics", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClassNameHeuristics classNameHeuristics0 = new ClassNameHeuristics();
      String[] stringArray0 = new String[9];
      ConfigurableHeuristics configurableHeuristics0 = classNameHeuristics0.configureHeuristic("regex", stringArray0);
      assertEquals("class-name", configurableHeuristics0.getName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClassNameHeuristics classNameHeuristics0 = new ClassNameHeuristics();
      ModificationType modificationType0 = ModificationType.DELETE;
      Modification modification0 = new Modification("heuristics.java.ClassNameHeuristics", "heuristics.java.ClassNameHeuristics", modificationType0, "heuristics.java.ClassNameHeuristics", "heuristics.java.ClassNameHeuristics");
      AnalysedFile analysedFile0 = new AnalysedFile(modification0);
      Boolean boolean0 = classNameHeuristics0.getRole(analysedFile0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ClassNameHeuristics classNameHeuristics0 = new ClassNameHeuristics();
      String string0 = classNameHeuristics0.getName();
      assertEquals("class-name", string0);
  }
}
