/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 29 17:08:32 GMT 2018
 */

package heuristics.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import heuristics.AnalysedFile;
import heuristics.ConfigurableHeuristics;
import heuristics.java.TypeAnnotationHeuristics;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.repodriller.domain.Modification;
import org.repodriller.domain.ModificationType;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TypeAnnotationHeuristics_ESTest extends TypeAnnotationHeuristics_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TypeAnnotationHeuristics typeAnnotationHeuristics0 = new TypeAnnotationHeuristics();
      String[] stringArray0 = new String[0];
      try { 
        typeAnnotationHeuristics0.configureHeuristic("", stringArray0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("heuristics.java.TypeAnnotationHeuristics", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[10];
      TypeAnnotationHeuristics typeAnnotationHeuristics0 = new TypeAnnotationHeuristics();
      ConfigurableHeuristics configurableHeuristics0 = typeAnnotationHeuristics0.configureHeuristic("names", stringArray0);
      assertEquals("type-annotation", configurableHeuristics0.getName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TypeAnnotationHeuristics typeAnnotationHeuristics0 = new TypeAnnotationHeuristics();
      ModificationType modificationType0 = ModificationType.COPY;
      Modification modification0 = new Modification("names", "names", modificationType0, "names", "names");
      AnalysedFile analysedFile0 = new AnalysedFile(modification0);
      Boolean boolean0 = typeAnnotationHeuristics0.getRole(analysedFile0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TypeAnnotationHeuristics typeAnnotationHeuristics0 = new TypeAnnotationHeuristics();
      String string0 = typeAnnotationHeuristics0.getName();
      assertEquals("type-annotation", string0);
  }
}
